[project]
name = "spiff-arena-common"
description = "Shared Python utilities for Spiff Arena frontend and backend components"
readme = "README.md"
requires-python = ">=3.10, <3.13"
dependencies = []
dynamic = ["version"]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
