name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI
on:
  release:
    types: [published]
jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history to find previous tags

      - name: Get previous tag
        id: previous_tag
        run: echo "PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^)" >> "$GITHUB_OUTPUT"

      - name: Check for changes in 'my-app' directory
        id: diff_check
        run: |
          if git diff --quiet ${{ steps.previous_tag.outputs.PREVIOUS_TAG }} HEAD -- my-app/; then
            echo "::set-output name=changed::false"
          else
            echo "::set-output name=changed::true"
          fi

      - name: Set up Python 3.12
        if: steps.diff_check.outputs.changed == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install pypa/build
        if: steps.diff_check.outputs.changed == 'true'
        run: pip install --constraint=.github/workflows/constraints.txt pip uv
      - name: Build a binary wheel and a source tarball
        if: steps.diff_check.outputs.changed == 'true'
        run: uv build spiff-arena-common
      - name: Publish distribution 📦 to PyPI
        if: steps.diff_check.outputs.changed == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          username: __token__
          password: ${{ secrets.COMMON_PYPI_KEY }}
